### ISSUE TITLE
Error loading thumbnails in couchpotato and plex views

### ISSUE THREAD

**Issue by lukeadair** [Hellowlol/HTPC-Manager#333]
I'm getting a 500 server error when loading images. The image url looks like this:

http://tower:8085/couchpotato/GetImage?w=100&h=150&url=[%22https://image.tmdb.org/t/p/w154/eMwotYpkcE42lGlaoCpPFaolvst.jpg%22,%22http://ia.media-imdb.com/images/M/MV5BMTc4ODc4NTQ1N15BMl5BanBnXkFtZTcwNDUxODUyMw@@._V1_.jpg%22,%22http://ia.media-imdb.com/images/M/MV5BMTc4ODc4NTQ1N15BMl5BanBnXkFtZTcwNDUxODUyMw@@._V1_SX300.jpg%22]

**Comment by Hellowlol** [comment]
Can you give me a debug log?

 Have you installed pil?

**Comment by Hellowlol** [comment]
That url works fine here.

**Comment by lukeadair** [comment]
Github won't let me attach the log. Do you have a preferred site that I should upload it to?

I don't think I have PIL installed. I installed HTPC Manager through an unraid plugin.

**Comment by Hellowlol** [comment]
Ok. Yes, please read https://github.com/Hellowlol/HTPC-Manager#so-you-found-a-bug-great

**Comment by brendann993** [comment]
I'm having this issue as well. The generated URL is 

```
/couchpotato/GetImage?w=100&h=150&url=["https://image.tmdb.org/t/p/w154/c6Nu7UjhGCQtV16WXabqOQfikK6.jpg","http://ia.media-imdb.com/images/M/MV5BMTc2NjMzOTE3Ml5BMl5BanBnXkFtZTcwMDE0OTc5Mw@@._V1_.jpg","http://ia.media-imdb.com/images/M/MV5BMTc2NjMzOTE3Ml5BMl5BanBnXkFtZTcwMDE0OTc5Mw@@._V1_SX300.jpg"]
```

It appears to be the [" and "] causing the issue as changing it to 

```
/couchpotato/GetImage?w=100&h=150&url=https://image.tmdb.org/t/p/w154/c6Nu7UjhGCQtV16WXabqOQfikK6.jpg
```

displays the image.
I have no idea where to change this those to fix it overall.

**Comment by Hellowlol** [comment]
Can you give me the exact URL that fails? And a log? Remember to clear the cache too :)

**Comment by brendann993** [comment]
When on "htpcmanagerURL/couchpotato" page no thumbnails are shown
<img width="960" alt="screen1" src="https://cloud.githubusercontent.com/assets/6630349/9547665/68be2042-4dce-11e5-9b4b-7b7a0436894b.png">
Exampe the first on on the list is
Full URL of image

```
http://10.1.1.150:8089/couchpotato/GetImage?w=100&h=150&url=[%22https://image.tmdb.org/t/p/w154/paS5plbzKz3PYddxky6svYYz3hS.jpg%22,%22http://ia.media-imdb.com/images/M/MV5BMTI4MzU5OTc2MF5BMl5BanBnXkFtZTYwNzQxMjc5._V1_.jpg%22,%22http://ia.media-imdb.com/images/M/MV5BMTI4MzU5OTc2MF5BMl5BanBnXkFtZTYwNzQxMjc5._V1_SX300.jpg%22]
```

URL doesn't work in chrome(just doesn't load), firefox (says the image has errors), IE (Same as chrome).
all the embeded urls appear to be the image in differet sizes and formats.
changing the url to include just one image and without [ ] or the " displays the image e.g

```
http://10.1.1.150:8089/couchpotato/GetImage?w=100&h=150&url=https://image.tmdb.org/t/p/w154/paS5plbzKz3PYddxky6svYYz3hS.jpg
```

This is the log. I have cleared the log and then reloaded the page.
http://pastebin.com/NN2N2pDi

**Comment by Hellowlol** [comment]
@brendann993 update to the latest commit. The string returning original image was removed so you can't be on the latest commit. Clear the cache and try again.

**Comment by brendann993** [comment]
I swear I had checked I was updated prior to posting haha. I've updated now and confirm this has fixed the issue for me :) great work as usual.

**Comment by Hellowlol** [comment]
Nice, my fork can also auto update ;) glad it's working as intended.

**Comment by brendann993** [comment]
Pretty sure I have auto update on though

**Comment by Hellowlol** [comment]
@Adair21 Still having this issue?

**Comment by lukeadair** [comment]
Yes, unfortunately I am. I updated to the latest branch about six days ago and I'm still getting broken images. It looks exactly like the screenshot from @brendann993 above. I will try to post a debug log when I get home tonight.

**Comment by Hellowlol** [comment]
Well that isnt the latest update. Can you make sure you update to the latest version before you post a debug log?

**Comment by lukeadair** [comment]
Yes, I will make sure I'm on the latest update before posting. Thanks!

**Comment by lukeadair** [comment]
Pastbin wouldn't let me upload the log, since it's over the size limit. I've uploaded it to dropbox.
https://www.dropbox.com/s/314dg3eyhhq2z09/htpcmanager.txt?dl=0

I'm on the latest version and I'm still seeing the issue.

![htpcmanager](https://cloud.githubusercontent.com/assets/867728/9674081/c36d4db8-5271-11e5-89a5-7b3e72ee94c3.jpg)

**Comment by Hellowlol** [comment]
Ok, wipe the log, set loglevel to debug, restart htpc manager then go to the plex module. Post a screenshot of the about page. I only have access to my cell and I don't want to open s 20mb log :P

**Comment by Hellowlol** [comment]
And a screenshot of you plex settings.

**Comment by Hellowlol** [comment]
@Adair21 Your pil/pillow install is broken/not working correctly

**Comment by lukeadair** [comment]
The issue is happening in both the plex and couchpotato modules.

Couchpotato Error
![htpcmanager-cp](https://cloud.githubusercontent.com/assets/867728/9674300/cbac8bb2-5274-11e5-9a0f-faff038d2a91.jpg)

Couchpotato Settings
![htpcmanager-cp-settings](https://cloud.githubusercontent.com/assets/867728/9674353/a7f7d202-5275-11e5-8fb6-23ec2973619a.jpg)

Plex
![htpcmanager-plex](https://cloud.githubusercontent.com/assets/867728/9674318/0efc30c0-5275-11e5-92d7-29c867f9dffa.jpg)

Plex Settings
![htpcmanager-plex-settings](https://cloud.githubusercontent.com/assets/867728/9674359/b68e2820-5275-11e5-8837-fc92540e0a08.jpg)

I cleared the debug log and visited the plex module. Here's that log: http://pastebin.com/bFvZRCRb

I then re-cleared the log and visited the couchpotato module. Here's that log: https://www.dropbox.com/s/j9trcdz8cmd14ba/htpcmanager-cp.txt?dl=0

The couchpotato log is 526kb (just over the pastebin limit of 512kb)

**Comment by madclicker** [comment]
You girls are starting to become a joke. This HUGE bug was fixed in PyTunes long ago, or just close the issue as usual.

**Comment by lukeadair** [comment]
I wasn't aware that pil/pillow was a requirement. Is that something I need to install separately?

**Comment by madclicker** [comment]
Yes, if you use a shit OS.

**Comment by lukeadair** [comment]
Did I do something to offend you? I'm using unraid 5

**Comment by Hellowlol** [comment]
@madclicker 

I cant fix something i cant find. If you already has fixed this, why dont you save us both some time and point me to commit where you fixed it or even better send a pr to correct my mistake(s)? :)

What do you mean when you say: "or just close this isse as usual" I dont close issues unless i think i have fixed it, if that isnt the case can you point me to the issue so i can rectify this?

@Adair21 I belive his comments im mainly meant for me. 

PIL/PIllow isnt required (but you should install it) however if it is installed, it needs to be installed correcly

**Comment by lukeadair** [comment]
i plan on upgrading to unraid 6 in the next few weeks, so I don't want to spend too much time on o setup that I won't be keeping. I'll report back if I'm still having issues on unraid 6. Thanks!

**Comment by Hellowlol** [comment]
Im still on a stock unraid 5 install. Waiting for a new drive so i can update. (no parity atm). Closing this as the error is related to pil and not to htpc manager.
