### ISSUE TITLE
sonarr style calender

### ISSUE THREAD

**Issue by tymanthius** [Hellowlol/HTPC-Manager#382]
One of the things I love about sonarr is it's colored calendar with cute little blocks. ;)

Would love to pull that into htpc, if at all possible.

**Comment by slamanna212** [comment]
agreed, its the only reason i still use the sonarr interface, adding that into HTPC manager would be amazing!

**Comment by Hellowlol** [comment]
Ye, it does look sweet. I'll look into that. No promises tho.

**Comment by tymanthius** [comment]
That's all we can ask.   Maybe you could cheat and just pull in the sonarr one directly.

**Comment by Hellowlol** [comment]
In a iframe? No thanks. It is possible to thAt already.

**Comment by Hellowlol** [comment]
This will be easy. Do you want one in the Dashboard too? Ill  add it to sickrage too.

**Comment by tymanthius** [comment]
In the dashboard sounds great.  :)    Esp. if options for daily/weekly/monthly are available.

Thank so much!!

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/issues/403

**Comment by Hellowlol** [comment]
Ill make all the options available in the module. I have to check how to do it in the dashboard. There is alot less space there so i have to see how that plays out.

**Comment by tymanthius** [comment]
Yea, that's why I'm thinking dashboard would be best to have daily, then module have weekly or monthly.  

At least for me.  ;)

**Comment by Hellowlol** [comment]
@tymanthius are you happy with the new calendar?

**Comment by tymanthius** [comment]
I turned it on in settings, and now I have a sonarr calendar link on the home page, and the tab on my sonarr (DVR) page. But it won't load anything.  The page stays blank.  

I restarted the VM too.

**Comment by Hellowlol** [comment]
disable use cnd and it should show up. I forgot to add the cnd links and just adds it locally.

**Comment by tymanthius** [comment]
That helped a lot. I like how yours shows time overlaps.

On the front page I have a blank white box even tho I have 2 shows today due at 8pm & 9pm (it's almost noon now).  Is that expected, or should it show the whole day?

**Comment by Hellowlol** [comment]
I'm not sure. Can I have a screenshot?

**Comment by tymanthius** [comment]
Here you go:  http://imgur.com/Jstv326

**Comment by my95z34** [comment]
Mine looks like that as well.

**Comment by Hellowlol** [comment]
Ah crap, I forgot about all the themes. I can change it so it shows more info.

**Comment by tymanthius** [comment]
Oh, and is the begining of week configurable?

**Comment by Hellowlol** [comment]
Nope, not atm.

**Comment by tymanthius** [comment]
No worries

**Comment by Hellowlol** [comment]
Do you have any issues with the calendar on the dashboard?

**Comment by Flippage** [comment]
Sonarr calendar not working on mine. Getting the same issue.
http://imgur.com/CKiOEOM

Am I missing something?

I installed HTPCManager by downloading the ZIP. Tried using the "Update" button within the app, but it doesnt seem to work. Do I need to Git-Clone to get the latest version ?

**Comment by Hellowlol** [comment]
The update button should work. Can you try to change theme to obsidion? I wondering if this is a css issue.
@Flippage Read https://github.com/Hellowlol/HTPC-Manager#so-you-found-a-bug-great and open a new issue please :)

**Comment by Flippage** [comment]
Updated to the "latest version" according to HTPCManager: http://imgur.com/jkIV4YL

( theme didn't seem to matter, though HTPCManager can't seem to detect my Git installation )

Calender on the dash is still the same. In the sonarr section it works perfectly.

Any ideas?

**Comment by Flippage** [comment]
Update!:

I changed the webdir to /htpc
Restarted, and the dashboard calendar is working now!

**Comment by Hellowlol** [comment]
lol wtf.. :P Well i had no idea what the error was caused by :P. You should use the git updater as the source updater can be buggy at times.

**Comment by Hellowlol** [comment]
@Flippage Thanks, i found the bug because of your comment :)

**Comment by Flippage** [comment]
Glad I could help. 

Probably the wrong place to ask, but I can't access htpc manager from my local network. I can access Sonarr and qbittorrent directly, but 10.0.0.2:8085 doesn't load anything on my iPhone. Do I need to run a separate webserver? Am I missing something ?

**Comment by Hellowlol** [comment]
Remember that you added a webdir so it would be http://ip:port/htpc

**Comment by Flippage** [comment]
Yeah I tried that. It never loads. Works fine on the local machine with http://localhost:8085 but I get nothing from remote.

**Comment by Hellowlol** [comment]
have you bound the interface on anything else then 0.0.0.0?

**Comment by Flippage** [comment]
Should I set all the modules to 0.0.0.0 as well? Or do they need to be localhost ? Right now htpcmanager is set to 10.0.0.2 but tried localhost and 0.0.0.0 as well. All to the same effect.

**Comment by Hellowlol** [comment]
In the modules it needs to be the ip to the program it should connect to. (it can be localhost if it on the same computer but its best to use the ip as the links will be broken if you are on another computer.).

In the general settings page you should not change the interface ip should be (0.0.0.0). You need to restart htpc manager after changing stuff on the general settings page :)

**Comment by Flippage** [comment]
Resolved. Thanks for the advice. I had to allow inbound port 8085 on my Windows firewall. Anyway you can incorporate this into the settings menu? Or the installation process?

E.g. When you enable webui for qbittorrent you get a Windows firewall prompt. Although now I'm clogging up an issue thread that is already resolved haha.

**Comment by Hellowlol** [comment]
Nope, that is something the user has to do them selves. :(

**Comment by Flippage** [comment]
Cool to add it to the readme on here? Or the wiki?

Other than that. Close this issue thread down :D

**Comment by Hellowlol** [comment]
That depends on your setup. I didnt have to open a port on my computer :)

**Comment by tymanthius** [comment]
Sorry I was away.  I'm still not getting anything on the front page of HTPC for sonarr calendar. Just now did a git pull, says I'm up to date (Current commit   6a78741eb94aa9cf74fb404a2da68336f119a73a).

I tried obsidian theme.  But no go.

EDIT:  Nevermind - apparently I just had to hit the month/day/week button and now it's working.

Sorry, was my bday weekend, brains are still slowly starting up.

**Comment by Hellowlol** [comment]
Happy birthday!

**Comment by Hellowlol** [comment]
@raysguy I dont know if you use htpc manager still use htpc manager or not but if you are would you like to style the sonarr calendar so it matches the themes? (the default is ok)

**Comment by Flippage** [comment]
Matching it to the themes would be cool. Or at least with the official sonarr calendar. It's just so clean.

Could the calendar show episodes as purple color when downloading (as per the official calendar) ?

Also, on the sonarr page in HTPCManager, you can select episodes in the calendar to pull up the episode menu and download, but on the dashboard calendar, you can't click on the episodes. Possible to change that as well ?

**Comment by Hellowlol** [comment]
1. Yes
2. Maybe, i have to see how much work it is :P

**Comment by thatbritguy** [comment]
@Hellowlol Hi there.  I haven't been using it too much for a while but just checked out the latest version. Calendar looks like a good addition.  What elements of it were you wanting theming? Do you just mean for the boxes in the calendar to match the colours used for the labels and buttons?  Let me know what you're thinking and I'll see what I can do.  Might take me a while to get to it though as I'm spending most of my online time at the moment building a wedding website for my sister.

In the meantime though I sent a PR adding the CDN for the calendar for you (couldn't get calendar to show at first then realised it's because I use CDN option).

**Comment by Hellowlol** [comment]
Yeah, that one slipped thru the cracks.. Sorry about that, the cnd option only exist because of you. :P,

**Comment by Hellowlol** [comment]
@raysguy I would happy if they just matched the backgroup colors etc of the theme so there is no white background on a dark theme.
